### ISSUE TITLE
Manifest v3

### ISSUE THREAD

**Issue by tomcollis** [fregante/browser-extension-template#55] opened 2021-10-02 09:15 UTC
I've just started experimenting with browser extensions and came across this from [OctoPrint - Open in Bundle Viewer](https://github.com/OctoPrint/Open-In-Bundle-Viewer) which was based on your template.

Do you have plans to update this template or rather recreate this template for version 3 of the manifest.json?

[Chrome Developers - Intro to Manifest v3](https://developer.chrome.com/docs/extensions/mv3/intro/)

**Comment by fregante** [comment] 2021-10-02 10:23
Thanks for opening the issue! 

The issue is that Parcel does not support the Manifest v3 yet so the only way to use v3 is to use webpack (or to avoid the WebExtension transformer, which would change the template substantially). This is tracked in https://github.com/parcel-bundler/parcel/issues/6079 and there's nothing that can be done in this repo unfortunately. 

You have until early 2022 to publish your v2 extension and then Parcel hopefully will update the transformer to support v3 before the "end of life for v2" in 2023.

If it's urgent, your only choice is to use a previous, webpack-based version. This is the last one before moving to Parcel: https://github.com/fregante/browser-extension-template/tree/a0f9cbe27c854e98d52033783a9e951246217dab

👆 but it's not advised at this point.

**Comment by fregante** [comment] 2021-10-02 10:24
### Please leave a 👍 on https://github.com/parcel-bundler/parcel/issues/6079 if you're interested

**Comment by tomcollis** [comment] 2021-10-11 15:34
Thank you, I have liked the issue you suggested.

**Comment by fregante** [comment] 2021-10-11 15:39
I'll keep this open until I update Parcel here if you don't mind.

**Comment by Andonvr** [comment] 2022-02-07 14:04
This is still a problem, and apparently the Chrome Web Store has stopped accepting new Manifest V2 extensions. Does this mean we cannot publish extensions that have been written with this template?
![image](https://user-images.githubusercontent.com/10791710/152802644-3a74d0a9-bc12-4564-92e2-c91f4d5a7be8.png)

**Comment by fregante** [comment] 2022-02-07 14:35
Unfortunately correct. There has been a PR on parcel's repo open for a while to add support

**Comment by phgn0** [comment] 2022-03-08 09:24
FYI for anyone looking for a hacky immediate workaround, you can manually patch the `@parcel/transformer-webextension` module via https://github.com/ds300/patch-package to recognize the new schema. It worked for me in https://github.com/lindylearn/annotations/commit/3bc830ebec053ca03cdfa1dd5dd9d1b067fe9305.

**Comment by aspiers** [comment] 2022-04-10 23:35
I see from [this comment 3 days ago](https://github.com/parcel-bundler/parcel/pull/7050#issuecomment-1092069575) that apparently all the work is done, and it's just awaiting final review.  Does this mean that until it's merged we can in theory just specify [a dependency on the GitHub PR branch](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls)?

**Comment by aspiers** [comment] 2022-04-10 23:49
Hrm, maybe not, since [`@parcel/transformer-webextension` is a separate package in a workspace subdirectory](@parcel/transformer-webextension), and I can't see any obvious way to specify a dependency on a subdirectory of a GitHub branch.  I notice that [this StackOverflow question](https://stackoverflow.com/questions/68138387/how-do-i-target-a-subdirectory-of-a-lerna-monorepo-when-targeting-installation) seems to ask how to do that, and didn't get any answers in 9 months, so maybe it's just not possible and [ds300/patch-package](https://github.com/ds300/patch-package) is the best way.

**Comment by fregante** [comment] 2022-04-11 01:10
Monorepos are a mess of tangled dependencies so I'd advise against trying to load that separately 😳 

Hopefully they're only a few days away from merging…

**Comment by aspiers** [comment] 2022-04-11 13:55
OK thanks for the advice! Yes hopefully indeed, since I'm working on an extension which I'd love to have published in the Chrome Web Store before a conference coming up soon...

**Comment by fregante** [comment] 2022-04-11 15:25
The PR has been merged. Try running this in a few hours:

```js
npm install -D parcel@nightly @parcel/config-webextension@nightly
```

**Comment by fregante** [comment] 2022-04-14 11:48
You can see the progress in the PR #75

However unfortunately it doesn't work due to:

- [x] https://github.com/parcel-bundler/parcel/issues/7952

**Comment by aspiers** [comment] 2022-04-25 23:35
What is left to do on this?

**Closed as completed** 2022-04-26 00:21 UTC

**Comment by fregante** [comment] 2022-04-26 00:23
Thanks for the ping! I updated parcel, tested it and it works as expected!

## Note 

This change effectively drops support for Firefox until they support Manifest v3: https://bugzilla.mozilla.org/show_bug.cgi?id=1578284

To enable support manually:

1. Run `npm run build`
2. In the `distribution/manifest.json` file, revert the same changes you see in [#75](https://github.com/fregante/browser-extension-template/pull/75):
	- set `manifest_version` to 2
	- move `host_permissions` items back to `permissions`
	- restore the previous `background` key
4. Save that version just for Firefox
