### ISSUE TITLE
change project description from webpack to parcel

### ISSUE THREAD

**Issue by aarmn** [fregante/browser-extension-template#63] opened 2022-02-20 21:04 UTC
I guess the title is trivial, 
📕 Barebones boilerplate with webpack, options handler, and auto-publishing
to
📕 Barebones boilerplate with parcel, options handler, and auto-publishing
and I posted a question in [here](https://github.com/parcel-bundler/parcel/discussions/7693) I would be glad if sb read that and tell me can this repo help me out with that or not.

**Comment by fregante** [comment] 2022-02-21 01:15
Duplicate of #61

**Closed as completed by fregante** 2022-02-21 01:15 UTC
